# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [16]:
s="Hi there Sam!"
s.split()

['Hi', 'there', 'Sam!']

*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [15]:
diameter=12742
planet="Earth"
txt="The diameter of the {} is {} kilometers"
print(txt.format(planet,diameter))


The diameter of the Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [13]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [14]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]["tricky"][3]['target'][3]


'hello'

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [12]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [10]:
import numpy as np
array=np.arange(20,35,2)
print(array)


[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
import numpy as np
x = np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [8]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a,b),axis=0)


array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [5]:
import pandas as pd 
data = {'Name':['Renault', 'Duster', 'Maruti'], 'Ratings':[9.0, 8.0, 5.0]}  
df = pd.DataFrame(data, index =['position1', 'position2', 'position3'])  
print(df)



              Name  Ratings
position1  Renault      9.0
position2   Duster      8.0
position3   Maruti      5.0


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [4]:
import pandas as pd
  
per1 = pd.date_range(start ='2023-01-01', 
         end ='2020-02-10')
  
for val in per1:
    print(val)

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [2]:

import pandas as pd 
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists, columns =['num1', 'alpha','num2']) 
print(df )

   num1 alpha  num2
0     1   aaa    22
1     2   bbb    25
2     3   ccc    24
